In [3]:
docs = ['go india',
		'india india',
		'hip hip hurray',
		'jeetega bhai jeetega india jeetega',
		'bharat mata ki jai',
		'kohli kohli',
		'sachin sachin',
		'dhoni dhoni',
		'modi ji ki jai',
		'inquilab zindabad']

In [4]:
from tensorflow.keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer()

In [5]:
tokenizer.fit_on_texts(docs)

In [6]:
len(tokenizer.word_index) #number of unique words in the whole doc

17

In [7]:
sequences = tokenizer.texts_to_sequences(docs)
sequences

[[9, 1],
 [1, 1],
 [3, 3, 10],
 [2, 11, 2, 1, 2],
 [12, 13, 4, 5],
 [6, 6],
 [7, 7],
 [8, 8],
 [14, 15, 4, 5],
 [16, 17]]

In [8]:
from keras.utils import pad_sequences
sequences = pad_sequences(sequences,padding='post')
sequences

array([[ 9,  1,  0,  0,  0],
       [ 1,  1,  0,  0,  0],
       [ 3,  3, 10,  0,  0],
       [ 2, 11,  2,  1,  2],
       [12, 13,  4,  5,  0],
       [ 6,  6,  0,  0,  0],
       [ 7,  7,  0,  0,  0],
       [ 8,  8,  0,  0,  0],
       [14, 15,  4,  5,  0],
       [16, 17,  0,  0,  0]], dtype=int32)

In [10]:
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding

model = Sequential()
model.add(Embedding(17,output_dim=2,input_length=5))
#output_dim is a hyperparameter, so you can convert the words to 2d, or 3d or any other dimension.

model.summary()

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding (Embedding)                │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [11]:
model.compile('adam','accuracy')

In [12]:
pred = model.predict(sequences)
print(pred)

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 747ms/step
[[[-0.02750437 -0.00240177]
  [ 0.02041848  0.03721343]
  [-0.04267768  0.02156195]
  [-0.04267768  0.02156195]
  [-0.04267768  0.02156195]]

 [[ 0.02041848  0.03721343]
  [ 0.02041848  0.03721343]
  [-0.04267768  0.02156195]
  [-0.04267768  0.02156195]
  [-0.04267768  0.02156195]]

 [[ 0.01334066  0.01742447]
  [ 0.01334066  0.01742447]
  [ 0.0474613   0.0276298 ]
  [-0.04267768  0.02156195]
  [-0.04267768  0.02156195]]

 [[ 0.04901722 -0.02569224]
  [-0.02787191 -0.04363897]
  [ 0.04901722 -0.02569224]
  [ 0.02041848  0.03721343]
  [ 0.04901722 -0.02569224]]

 [[ 0.0345072   0.00541909]
  [-0.00250747 -0.02979354]
  [ 0.03982501  0.00093224]
  [ 0.04930884  0.01562795]
  [-0.04267768  0.02156195]]

 [[-0.03277371 -0.03452772]
  [-0.03277371 -0.03452772]
  [-0.04267768  0.02156195]
  [-0.04267768  0.02156195]
  [-0.04267768  0.02156195]]

 [[-0.0433763  -0.00231892]
  [-0.0433763  -0.00231892]
  [-0.04267768  0.02156195]
  [-0.04267768  0.0215619

In [14]:
from keras.datasets import imdb
from tensorflow.keras.preprocessing.text import Tokenizer
from keras.utils import pad_sequences
from keras import Sequential
from keras.layers import Dense,SimpleRNN,Embedding,Flatten

In [15]:
(X_train,y_train),(X_test,y_test) = imdb.load_data()

17464789/17464789 ━━━━━━━━━━━━━━━━━━━━ 2s 0us/step


In [16]:
X_train = pad_sequences(X_train,padding='post',maxlen=50)
X_test = pad_sequences(X_test,padding='post',maxlen=50)

In [17]:
X_train.shape

(25000, 50)

In [19]:
model = Sequential()
model.add(Embedding(10000, 2,input_length=50)) #conisdering the number of unique words to be 10000, output_dim = 2, and each review having 50 words each (after padding)
model.add(SimpleRNN(32,return_sequences=False))
model.add(Dense(1, activation='sigmoid'))

model.summary()

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)              │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ simple_rnn (SimpleRNN)               │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [20]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['acc'])
history = model.fit(X_train, y_train,epochs=5,validation_data=(X_test,y_test))

Epoch 1/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 11s 11ms/step - acc: 0.5746 - loss: 0.6554 - val_acc: 0.7986 - val_loss: 0.4369
Epoch 2/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 7s 8ms/step - acc: 0.8259 - loss: 0.3986 - val_acc: 0.8033 - val_loss: 0.4376
Epoch 3/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 10s 8ms/step - acc: 0.8580 - loss: 0.3424 - val_acc: 0.8032 - val_loss: 0.4381
Epoch 4/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - acc: 0.8678 - loss: 0.3234 - val_acc: 0.7881 - val_loss: 0.5132
Epoch 5/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 6s 7ms/step - acc: 0.8835 - loss: 0.2951 - val_acc: 0.7791 - val_loss: 0.5340


In [23]:
import numpy as np
import tensorflow as tf

def preprocess_and_predict(review, tokenizer, model, max_len):
    """
    Preprocesses a new review, converts it to sequences, applies padding,
    and predicts sentiment using the trained model.

    Parameters:
    review (str): The input text review.
    tokenizer (Tokenizer): The tokenizer used during training.
    model (tf.keras.Model): The trained sentiment analysis model.
    max_len (int): Maximum sequence length for padding.

    Returns:
    str: "Positive" or "Negative" sentiment prediction.
    """
    tokenizer.fit_on_texts(docs)
    # Convert review to sequences
    sequence = tokenizer.texts_to_sequences([review])
    # Pad sequence
    padded_sequence = tf.keras.preprocessing.sequence.pad_sequences(sequence, maxlen=max_len, padding='post')
    # Predict sentiment
    prediction = model.predict(padded_sequence)[0][0]  # Extracting the probability score

    # Interpret prediction
    sentiment = "Positive" if prediction >= 0.5 else "Negative"
    return sentiment

# Example usage
new_review = input("Enter a new review: ")
sentiment = preprocess_and_predict(new_review, tokenizer, model, 50)
print(f"Predicted Sentiment: {sentiment}")


Enter a new review: movie was good
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step
Predicted Sentiment: Positive
