In [23]:
#LEARNING THE PREPROCESSING OF TEXTUAL DATA
import numpy as np

#we are having different reviews/ datapoints
docs = ['go india',
		'india india',
		'hip hip hurray',
		'jeetega bhai jeetega india jeetega',
		'bharat mata ki jai',
		'kohli kohli',
		'sachin sachin',
		'dhoni dhoni',
		'modi ji ki jai',
		'inquilab zindabad']

In [24]:
from tensorflow.keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer(oov_token='nothing')
'''
oov_token = 'nothing' means that if after training, a new word comes, it gets simply replaced by 'nothing', which was a word already used during training.
in place of 'nothing', you can put any word.
'''

"\noov_token = 'nothing' means that if after training, a new word comes, it gets simply replaced by 'nothing', which was a word already used during training. \nin place of 'nothing', you can put any word. \n"

In [25]:
tokenizer.fit_on_texts(docs)
'''
handles all behind the scenes data preprocessing, like seperating each word, turning all letters to lowercase, giving each word an index.
NOTE:- here, we are doing integer encoding, which means that each unique word gets "ONE" unique integer.
'''

'\nhandles all behind the scenes data preprocessing, like seperating each word, turning all letters to lowercase, giving each word an index. \nNOTE:- here, we are doing integer encoding, which means that each unique word gets "ONE" unique integer. \n'

In [26]:
tokenizer.word_index

{'nothing': 1,
 'india': 2,
 'jeetega': 3,
 'hip': 4,
 'ki': 5,
 'jai': 6,
 'kohli': 7,
 'sachin': 8,
 'dhoni': 9,
 'go': 10,
 'hurray': 11,
 'bhai': 12,
 'bharat': 13,
 'mata': 14,
 'modi': 15,
 'ji': 16,
 'inquilab': 17,
 'zindabad': 18}

In [27]:
tokenizer.word_counts
'''
gives us the frequency of words repeated
'''

'\ngives us the frequency of words repeated \n'

In [28]:
tokenizer.document_count
'''
number of datapoints or reviews
'''

'\nnumber of datapoints or reviews \n'

In [29]:
sequences = tokenizer.texts_to_sequences(docs)
sequences
'''
converts the reviews into list of indices given to the words.
for eg:-
"go india" ---> 10 2
where 10 is the index of "go" and 2 is the index of "india"
'''

'\nconverts the reviews into list of indices given to the words. \nfor eg:- \n"go india" ---> 10 2\nwhere 10 is the index of "go" and 2 is the index of "india"\n'

In [30]:
from keras.utils import pad_sequences

In [31]:
sequences = pad_sequences(sequences,padding='post') #converts all the reviews into same length by inserting extra zeroes at the end.

In [32]:
sequences

array([[10,  2,  0,  0,  0],
       [ 2,  2,  0,  0,  0],
       [ 4,  4, 11,  0,  0],
       [ 3, 12,  3,  2,  3],
       [13, 14,  5,  6,  0],
       [ 7,  7,  0,  0,  0],
       [ 8,  8,  0,  0,  0],
       [ 9,  9,  0,  0,  0],
       [15, 16,  5,  6,  0],
       [17, 18,  0,  0,  0]], dtype=int32)

In [33]:
#SENTIMENT ANALYSIS PROJECT
from keras.datasets import imdb
from keras import Sequential
from keras.layers import Dense,SimpleRNN,Embedding,Flatten

In [34]:
(X_train,y_train),(X_test,y_test) = imdb.load_data()

In [36]:
len(X_train[2])

141

In [37]:
X_train = pad_sequences(X_train,padding='post',maxlen=50)
X_test = pad_sequences(X_test,padding='post',maxlen=50)
'''
we want to keep the length of each review to be 50, and add extra zeroes at the end if lacking.
'''

'\nwe want to keep the length of each review to be 50, and add extra zeroes at the end if lacking. \n'

In [38]:
X_train[0]

array([2071,   56,   26,  141,    6,  194, 7486,   18,    4,  226,   22,
         21,  134,  476,   26,  480,    5,  144,   30, 5535,   18,   51,
         36,   28,  224,   92,   25,  104,    4,  226,   65,   16,   38,
       1334,   88,   12,   16,  283,    5,   16, 4472,  113,  103,   32,
         15,   16, 5345,   19,  178,   32], dtype=int32)

In [35]:
X_train[0] #no use of tokenizer as the data is already preprocessed, as in, already integer encoded. so, when we print each review, all the words get represented by integers.

[1,
 14,
 22,
 16,
 43,
 530,
 973,
 1622,
 1385,
 65,
 458,
 4468,
 66,
 3941,
 4,
 173,
 36,
 256,
 5,
 25,
 100,
 43,
 838,
 112,
 50,
 670,
 22665,
 9,
 35,
 480,
 284,
 5,
 150,
 4,
 172,
 112,
 167,
 21631,
 336,
 385,
 39,
 4,
 172,
 4536,
 1111,
 17,
 546,
 38,
 13,
 447,
 4,
 192,
 50,
 16,
 6,
 147,
 2025,
 19,
 14,
 22,
 4,
 1920,
 4613,
 469,
 4,
 22,
 71,
 87,
 12,
 16,
 43,
 530,
 38,
 76,
 15,
 13,
 1247,
 4,
 22,
 17,
 515,
 17,
 12,
 16,
 626,
 18,
 19193,
 5,
 62,
 386,
 12,
 8,
 316,
 8,
 106,
 5,
 4,
 2223,
 5244,
 16,
 480,
 66,
 3785,
 33,
 4,
 130,
 12,
 16,
 38,
 619,
 5,
 25,
 124,
 51,
 36,
 135,
 48,
 25,
 1415,
 33,
 6,
 22,
 12,
 215,
 28,
 77,
 52,
 5,
 14,
 407,
 16,
 82,
 10311,
 8,
 4,
 107,
 117,
 5952,
 15,
 256,
 4,
 31050,
 7,
 3766,
 5,
 723,
 36,
 71,
 43,
 530,
 476,
 26,
 400,
 317,
 46,
 7,
 4,
 12118,
 1029,
 13,
 104,
 88,
 4,
 381,
 15,
 297,
 98,
 32,
 2071,
 56,
 26,
 141,
 6,
 194,
 7486,
 18,
 4,
 226,
 22,
 21,
 134,
 476,
 26,
 480,
 5

In [39]:
model = Sequential()

model.add(SimpleRNN(32,input_shape=(50,1),return_sequences=False))
model.add(Dense(1,activation='sigmoid'))

model.summary()

'''
input shape = (number of timesteps, number of input features)
50 ---> number of timesteps being number of words in each review
1 ---> number of input features as in length of each encoded word is 1.
if we see the book example, "movie was good"
movie = [1 0 0 0 0]
so, timesteps for this review was 3 and there were 5 input features as each word goes one by one being the input and each word represented by 5 integers here.
'''

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ simple_rnn_1 (SimpleRNN)             │ (None, 32)                  │           1,088 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 1)                   │              33 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 1,121 (4.38 KB)

 Trainable params: 1,121 (4.38 KB)

 Non-trainable params: 0 (0.00 B)

'\ninput shape = (number of timesteps, number of input features)\n50 ---> number of timesteps being number of words in each review\n1 ---> number of input features as in length of each encoded word is 1. \nif we see the book example, "movie was good" \nmovie = [1 0 0 0 0]\nso, timesteps for this review was 3 and there were 5 input features as each word goes one by one being the input and each word represented by 5 integers here. \n'

In [40]:
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

model.fit(X_train,y_train,epochs=5,validation_data=(X_test,y_test))

Epoch 1/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 17s 15ms/step - accuracy: 0.4962 - loss: 0.7179 - val_accuracy: 0.5060 - val_loss: 0.6942
Epoch 2/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 9s 11ms/step - accuracy: 0.5093 - loss: 0.6931 - val_accuracy: 0.5092 - val_loss: 0.6933
Epoch 3/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 10s 11ms/step - accuracy: 0.5096 - loss: 0.6927 - val_accuracy: 0.5026 - val_loss: 0.6939
Epoch 4/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 10s 12ms/step - accuracy: 0.5046 - loss: 0.6925 - val_accuracy: 0.5056 - val_loss: 0.6938
Epoch 5/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 10s 13ms/step - accuracy: 0.5134 - loss: 0.6920 - val_accuracy: 0.5024 - val_loss: 0.6937


In [46]:
y_pred = model.predict(X_test)

782/782 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step


In [47]:
y_pred

array([[0.5062803],
       [0.5062803],
       [0.5062803],
       ...,
       [0.5062803],
       [0.5062803],
       [0.5062803]], dtype=float32)

In [49]:
import numpy as np
import tensorflow as tf

# Function to preprocess and predict sentiment of a new review
def predict_review_sentiment(review, tokenizer, model, max_len):
    """
    Takes a new review, tokenizes it, pads it, and predicts sentiment.

    Parameters:
    review (str): The input text review.
    tokenizer (Tokenizer): The tokenizer used during training.
    model (tf.keras.Model): The trained sentiment analysis model.
    max_len (int): Maximum sequence length for padding.

    Returns:
    str: "Positive" or "Negative" sentiment prediction.
    """
    tokenizer = Tokenizer(oov_token='nothing')
    tokenizer.fit_on_texts([review])
    # Convert review to sequences
    sequence = tokenizer.texts_to_sequences([review])
    print(sequence)
    # Pad sequence
    padded_sequence = tf.keras.preprocessing.sequence.pad_sequences(sequence, maxlen=max_len, padding='post')
    # Predict sentiment
    print(padded_sequence)
    prediction = model.predict(padded_sequence)

    # Interpret prediction
    sentiment = "Positive" if prediction >= 0.5 else "Negative"
    return sentiment

# Example usage
new_review = input("Enter a new review: ")
sentiment = predict_review_sentiment(new_review, tokenizer, model, 50)
print(f"Predicted Sentiment: {sentiment}")


Enter a new review: movie was really good
[[2, 3, 4, 5]]
[[2 3 4 5 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step
Predicted Sentiment: Positive
